### ISSUE TITLE
Timezone dropdown is not setting local times correctly on load

### ISSUE THREAD

**Issue by aarongustafson** [PWA-Summit/pwasummit.org#37]
@webmaxru mentioned this is an issue he’s seeing.

@Snugug can you take a look? I think you wrote the logic originally.

**Comment by webmaxru** [comment]
I found out that the issue is with initial calculation only - it just doesn't happen, the first session is always 2am regardless of the local timezone (so there is no bug for devices in PT timezone). Calculations after explicit timezone selector toggle, change time offset correctly (but because of the wrong initial mapping the resulting displayed time is incorrect)
